
spring.data.mongodb.uri=mongodb+srv://owlsyncar:O80MV5Rot7a04Q9l@estilourbano.n4ufdg7.mongodb.net/?retryWrites=true&w=majority&appName=estilourbano
server.port=9000
spring.data.mongodb.database=estilourbano